### ISSUE TITLE
Import error when importing as a library dependency

### ISSUE THREAD

**Issue by aeggersie** [FlorisHoogenboom/som-anomaly-detector#4]
In case this project is used as a library and installed via python requirements, the internal imports cannot be resolved. 

It can be given as python dependency as follows: 
`git+git://github.com/FlorisHoogenboom/som-anomaly-detector@master#egg=som_anomaly_detector-1.0`

**Proposed solution**
The issue can be solved by replacing the first line of the som_anomaly_detection.AnomalyDetection

`from KohonenSom import KohonenSom`
by
`from som_anomaly_detector.KohonenSom import KohonenSom`

as the base path would be `som_anomaly_detector`

Please review this issue and fix when possible. Thank you!

**Comment by FlorisHoogenboom** [comment]
Thnx for pointing this out. It should be resolved by 2e30bdf81ce9466bd20812600ee85e2ac21019ba

**Comment by aeggersie** [comment]
> Thnx for pointing this out. It should be resolved by [2e30bdf](https://github.com/FlorisHoogenboom/som-anomaly-detector/commit/2e30bdf81ce9466bd20812600ee85e2ac21019ba)

Great, thank you for resolving the issue!
